### ISSUE TITLE
Missing Nova 4 badge on novapackage.com

### ISSUE THREAD

**Issue by mrleblanc101** [Muetze42/nova-values-field#7]
The packages is not shown as Nova 4 compatible on https://novapackages.com/packages/norman-huth/nova-values-field
<img width="348" alt="Capture d’écran, le 2022-10-25 à 09 34 05" src="https://user-images.githubusercontent.com/17392251/197787609-c1a909a1-f0f4-49c8-9b69-7e25f8a6bd93.png">
<img width="342" alt="Capture d’écran, le 2022-10-25 à 09 34 11" src="https://user-images.githubusercontent.com/17392251/197787619-86924489-6f3b-4cef-9f6f-13c7de190840.png">

**Comment by dmason30** [comment]
The version is extracted from composer require:
https://github.com/tighten/novapackages/blob/c5d1a4fdaa822706d29bee56f6758d21fc06b9fb/app/Jobs/SyncPackagePackagistData.php#L47-L50

**Comment by mrleblanc101** [comment]
@dmason30 Thanks, I opened a PR which add the dependency on `"laravel/nova": "^4.0",`

**Comment by Muetze42** [comment]
Thanks for the info. I wanted to revise the package once anyway. Then I will of course update the requirements at the same time

**Comment by mrleblanc101** [comment]
@dmason30 Are you sure there is nothing else ?
https://novapackages.com/packages/norman-huth/nova-values-field
novapackages.com see the new version and the `laravel/nova ^4.0` requirement, but still no "Nova 4 compatible" tag on the listing.

**Comment by Muetze42** [comment]
Maybe it will take a while until it is updated there.

In my opinion, you could generally suggest Tighten  a refactor of the Novapackages site.  
Especially due to the growing community and the differences between Nova Orion & Nova Sivler Surver could be made clearer and more comfortable.

Maybe also a snipped section or so. I have so much stuff lying around. But creating a package always costs time, maintenance and so on and is not worth it in every case....

**Comment by dmason30** [comment]
> @dmason30 Are you sure there is nothing else ? https://novapackages.com/packages/norman-huth/nova-values-field novapackages.com see the new version and the `laravel/nova ^4.0` requirement, but still no "Nova 4 compatible" tag on the listing.

Checking their console they sync the data every 2-3 hours

**Comment by mrleblanc101** [comment]
Weird, I swear I was seeing the updated `1.0.2` version, `published: 25min ago` and `nova version: ^4.0` this morning but now it's back to `1.0.1` and `published: 5 months ago` and no `nova version`. That's why I was surprised to not see the `Nova 4 compatible` tag.
I'll check back tomorrow if it get indexed, thanks !
